version: '3.8'

networks:
    webapp:

services:
    nginx:
        image: nginx:stable
        container_name: ${APP_NAME}_nginx
        ports:
            - "8080:80"
        links:
            - php
        volumes:
            - shared-data:/var/www/html
            -   type: bind
                source: .docker/nginx/site.conf
                target: /etc/nginx/conf.d/default.conf
            - ./.docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php
        networks:
            - webapp
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - shared-data:/var/www/html
        container_name: ${APP_NAME}_php
        environment:
            - APP_ENV=${APP_ENV}
        ports:
            - "9001:9000"
        networks:
            - webapp
volumes:
    shared-data:
